### PR TITLE
Tab1-updates-Team1-Project1

### PR DESCRIPTION
**Pull request by Saroj4545**
UI updates for Project 1 from Team 1.

### CODE REVIEW

**Comment by KINGTUT10101** [comment]
I was able to run the GUI with no issues, although I didn't get a chance to test if it's actually functional. Can you describe the changes you made and what issue this resolves, please?

You guys also need to resolve the conflicts before changes can be pushed the main.

**Comment by KINGTUT10101** [comment]
This is what my GUI looks like for any other reviewers looking at this:
image

**Comment by KINGTUT10101** [comment]
I did notice that it crashes when I some of the buttons, like "Read my mind", "Execute", and "Not what I was thinking".

`Traceback (most recent call last):
  File "/home/terwalwq/Documents/Git/temp/Saroj_Avatar/brainwave_reading_tab.py", line 165, in read_mind
    self.prediction_label = prediction_response['prediction_label']
                            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Aborted (core dumped)`

I would suggest adding some error handling to this to save everyone some sanity if you have time.

**Comment by Saroj4545** [comment]
Hi,
For Project1 we were updating the UI for the tab1. Should I add a try
statement to catch the error and log it to the console like in the
attachment? I can push this change to the same open PR.

Thank you for the review.

Regards,
Saroj Khatri

**Comment by Saroj4545** [comment]
> This is what my GUI looks like for any other reviewers looking at this: image

Adding updated UI from this PR for reference:
UI

**Comment by Saroj4545** [comment]
> I did notice that it crashes when I some of the buttons, like "Read my mind", "Execute", and "Not what I was thinking".
> 
> `Traceback (most recent call last): File "/home/terwalwq/Documents/Git/temp/Saroj_Avatar/brainwave_reading_tab.py", line 165, in read_mind self.prediction_label = prediction_response['prediction_label'] ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable Aborted (core dumped)`
> 
> I'm not sure if this still happens when the GUI is hooked up to actual data, but I would suggest adding some error handling to this to save everyone some sanity if you have time.

Yes the errors are due to actual data not getting found when executing the click on the buttons. I have added catch blocks on the button functions to console log the errors when the response is undefined so it wont crash the window.

**Comment by KINGTUT10101** [comment]
Okay, I tried running it again today but my QT installation is giving me trouble. Someone else will need to take a look at this for now until I figure out the problem.

**Comment by 3C-SCSU** [comment]
*** Important: closing this pull request. Do not merge. This ticket was already solved and merged with a version implemented that doesn't cause any conflicts.

**Pull request closed without merging**
